allowBuilds:
  es5-ext: false
  esbuild: true
  skl-docs: true
  vue-demi: false
minimumReleaseAge: 1440
overrides:
  esbuild: '>=0.28.2'
  vite: '>=8.2.2'
  vitepress-versioning-plugin>vitepress-versioning-plugin: 1.3.0
